version: 1.0.{build}
image:
- Ubuntu

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      MY_VAR: value1
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      MY_VAR: value3
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      MY_VAR: value4

build_script:
  - ps: go build

test_script:
  - ps: go build

deploy_script:
  - ps: go build
