version: 1.0.{build}
image:
- Ubuntu

environment:
  matrix:
    - GETH_ARCH: amd64
      GETH_CC: C:\msys64\mingw64\bin\gcc.exe
      PATH: C:\msys64\mingw64\bin;C:\Program Files (x86)\NSIS\;%PATH%

install:
  - git submodule update --init --depth 1 --recursive
  - go version

build_script:
  - ps: go build

test_script:
  - ps: go build

deploy_script:
  - ps: go build
