version: 1.0.{build}
image:
- Visual Studio 2017
- Ubuntu

environment:
  matrix:
    - ARCH: arm
    - ARCH: arm64
    - ARCH: amd64
    - GETH_ARCH: amd64
      GETH_CC: C:\msys64\mingw64\bin\gcc.exe
      PATH: C:\msys64\mingw64\bin;C:\Program Files (x86)\NSIS\;%PATH%

install:
  - git submodule update --init --depth 1 --recursive
  - go version

matrix:
  exclude:
    - image: Visual Studio 2017
      ARCH: arm
    - image: Visual Studio 2017
      ARCH: arm64

build_script:
  - ps: make

test_script:
  - ps: make

deploy_script:
  - ps: make
