clone_depth: 5
version: "{branch}.{build}"

image:
  - Visual Studio 2019

environment:
  matrix:
    - GETH_ARCH: amd64
      GETH_CC: C:\msys64\mingw64\bin\gcc.exe
      PATH: C:\msys64\mingw64\bin;C:\Program Files (x86)\NSIS\;%PATH%

install:
  - git submodule update --init --depth 1 --recursive
  - go version

build_script:
  - ps: $env:VERSION = "$(git describe --always)"
  - go run build\ci.go install -dlgo -arch %GETH_ARCH% -cc %GETH_CC%
  - 7z a open-etc-pool-friends-win64-%VERSION%.zip .\build\bin\geth.exe
  - ps: Get-FileHash open-etc-pool-friends-win64-$env:VERSION.zip -Algorithm SHA256
  - ps: Get-FileHash open-etc-pool-friends-win64-$env:VERSION.zip -Algorithm SHA256 | Out-File open-etc-pool-friends-win64-$env:VERSION.zip.sha256
  - 7z a open-etc-pool-friends-alltools-win64-%VERSION%.zip .\build\bin\*
  - ps: Get-FileHash open-etc-pool-friends-alltools-win64-$env:VERSION.zip -Algorithm SHA256
  - ps: Get-FileHash open-etc-pool-friends-alltools-win64-$env:VERSION.zip | Out-File open-etc-pool-friends-alltools-win64-$env:VERSION.zip.sha256

for:
  - branches:
      only:
        - /v\d*\.\d*\.\d*.*/
    artifacts:
      - path: '*open-etc-pool-friends-win64*.zip'
        name: geth
      - path: '*open-etc-pool-friends-win64*.zip.sha256'
        name: geth-sha256
      - path: '*open-etc-pool-friends-alltools*.zip'
        name: alltools
      - path: '*open-etc-pool-friends-alltools*.zip.sha256'
        name: alltools-sha256

deploy:
  provider: GitHub
  repository: yuriy0803/open-etc-pool-friends
  artifact: /open-etc-pool-friends.*-win64-.*\.zip.*/
  draft: true
  on:
    appveyor_repo_tag: true
