version: 1.0.{build}
image:
- Ubuntu

environment:
  matrix:
    - ARCH: arm
    - ARCH: arm64
    - ARCH: amd64

matrix:
  exclude:
      ARCH: arm64

build_script:
  - ps: go build

test_script:
  - ps: go build

deploy_script:
  - ps: go build
